name: Java homework

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
  
jobs:
  build_test:
    runs-on: ubuntu-22.04

    steps:
    - name: code check
      uses: actions/checkout@v4

    - name: set up Java 17 Temurin
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: build 
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn test
    - run: java -jar ./target/*.jar --server.port=8080
    - run: curl -s 'http://localhost:8080/actuator/health'

      
