name: Continuous Integration
on:
  push:
    branches:
      - main
      - jenk
  workflow_dispatch:

jobs:
  my_first_job:
    runs-on: ubuntu-latest

    steps:
    - name: install checkout@v4
      uses: actions/checkout@v4

    - name: set up Java 17 Zulu
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'maven'
        
    - name: show java version
      run: "java -version"

    - name: show maven
      run: "mvn -version"

    - name: chmod
      run: "chmod 755 ./mvnw"

#    - name: ./mvnw
#      run: "./mvnw clean package"

    - run: ls -al

      
