name: Java homework

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
  
jobs:
  my_first_job:
    runs-on: ubuntu-latest

    steps:
    - name: code check
      uses: actions/checkout@v4

    - name: set up Java 17 Temurin
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: show java version
      run: "java -version"

    - run: "ls -al"

    - name: build 
      run: "mvn -B package --file pom.xml"

    - name: Run tests
      run: "mvn test"


      
